export QINIU_ACCESS_KEY="<ACCESS KEY>"
export QINIU_SECRET_KEY="<SECRET KEY>"
export QINIU_TEST_BUCKET="<BUCKET NAME>"
export QINIU_TEST_DOMAIN="<BUCKEY DOMAIN>"

export QINIU_PILI_ACCESS_KEY="<PILI ACCESS KEY>"
export QINIU_PILI_SECRET_KEY="<PILI SECRET KEY>"
